# Generated by Django 2.2.24 on 2022-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Новостройка'), (False, 'Старое здание'), (None, 'Неизвестно')], null=True, verbose_name='New building:'),
        ),
    ]
