# Generated by Django 2.2.24 on 2022-11-29 13:00

from django.db import migrations


def fill_building_type(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year < 2015:
            flat.new_building = False
        else:
            flat.new_building = True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_building_type),
    ]
